name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ensure pnpm is available before Node action tries to resolve pnpm cache
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test -- --ci
        env:
          CI: true

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: junit/junit.xml

      - name: Build (push)
        if: github.event_name != 'pull_request'
        run: pnpm build
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}

      - name: Build (PR; mocks only)
        if: github.event_name == 'pull_request'
        run: pnpm build
